[package]
name = "bitarray-naive"
version = "0.1.1"
edition = "2021"
description = "The simple and naive rust implementation of a bitarray."
license-file = "LICENSE"
repository = "https://github.com/obakhmach/bitarray"


[dependencies]
serde = {version = "1.0.151", features = ["derive"]}