[package]
name = "bitarray"
version = "0.1.0"
edition = "2021"
description = "The simple and naive rust implementation of a bitarray."
license-file = "LICENSE"
repository = "https://github.com/obakhmach/bitarray"


[dependencies]
